### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by mohkah4** [arashnm80/python-tutorial#3]
سلام استاد حلقه املا اش  غلطه

**Comment by arashnm80** [comment]
اره درسته. حالا ببین خودت میتونی توی یه pull request درستش کنی؟

**Comment by arashnm80** [comment]
نمونه اش رو توی ویدیو انجام دادم

**Comment by mohkah4** [comment]
I did it😎

در تاریخ یکشنبه ۲۶ فوریهٔ ۲۰۲۳،‏ ۰۱:۳۱ Arash Nemat Zadeh <
***@***.***> نوشت:

**Comment by arashnm80** [comment]
اره دیدم. الان تو اون نسخه ای که برای خودت از من کپی گرفتی تصحیحش کردی. حالا باید درخواست بدی که اون تغییر بیاد تو نسخه من هم اعمال بشه.

**Comment by mohkah4** [comment]
الان ارسال شد؟

در تاریخ یکشنبه ۲۶ فوریهٔ ۲۰۲۳،‏ ۰۱:۳۱ Arash Nemat Zadeh <
***@***.***> نوشت:

**Comment by arashnm80** [comment]
تایید کردم. آفرین.
#4

**Comment by mohkah4** [comment]
خدایی استاد نمیدونم چه حس ذوقی بود ساعت دو شب نشستم با اون ور رفتم درستش
کنم...❤
تا حالا تو عمرم واس ی غلط املایی وقت نذاشته بودم😂

در تاریخ یکشنبه ۲۶ فوریهٔ ۲۰۲۳،‏ ۰۲:۰۶ Arash Nemat Zadeh <
***@***.***> نوشت:

**Comment by arashnm80** [comment]
😂✌
